### ISSUE TITLE
Build failure for Custom topic

### ISSUE THREAD

**Issue by Prj1508** [AuroAi/apollo_ros_bridge#10]
The error message now is
INFO: Reading 'startup' options from /home/apollo_ros_bridge/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (10-29 18:55:21.102) Found 2 targets...
ERROR: (10-29 18:55:26.198) /home/apollo_ros_bridge/cyber_ros_bridge/lib/BUILD:4:1: C++ compilation of rule '//cyber_ros_bridge/lib:cyber_ros_bridge_lib' failed (Exit 1).
cyber_ros_bridge/lib/module_drivers.cpp: In function 'void cyber_ros_bridge::ApolloImuToROSImu(const std::shared_ptr<apollo::drivers::gnss::Imu>&, sensor_msgs::Imu&)':
cyber_ros_bridge/lib/module_drivers.cpp:197:21: warning: typedef 'byte' locally defined but not used [-Wunused-local-typedefs]
     typedef uint8_t byte;
                     ^
cyber_ros_bridge/lib/module_drivers.cpp: In function 'void cyber_ros_bridge::ApolloChassisToROSChassis(const std::shared_ptr<apollo::canbus::Chassis>&, chassis_msgs::chassis&)':
cyber_ros_bridge/lib/module_drivers.cpp:251:32: error: cannot convert 'apollo::canbus::Chassis::engine_started' from type 'bool (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_engine_started_type {aka unsigned char}'
     chassis_ros.engine_started = chassis_msg->engine_started;
                                ^
cyber_ros_bridge/lib/module_drivers.cpp:252:28: error: cannot convert 'apollo::canbus::Chassis::engine_rpm' from type 'float (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_engine_rpm_type {aka double}'
     chassis_ros.engine_rpm = chassis_msg->engine_rpm;
                            ^
cyber_ros_bridge/lib/module_drivers.cpp:253:28: error: cannot convert 'apollo::canbus::Chassis::speed_mps' from type 'float (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_speed_mps_type {aka double}'
     chassis_ros.speed_mps  = chassis_msg->speed_mps;
                            ^
cyber_ros_bridge/lib/module_drivers.cpp:254:29: error: cannot convert 'apollo::canbus::Chassis::odometer_m' from type 'float (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_odometer_m_type {aka double}'
     chassis_ros.odometer_m  = chassis_msg->odometer_m;
                             ^
cyber_ros_bridge/lib/module_drivers.cpp:255:38: error: cannot convert 'apollo::canbus::Chassis::throttle_percentage' from type 'float (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_throttle_percentage_type {aka double}'
     chassis_ros.throttle_percentage  = chassis_msg->throttle_percentage;
                                      ^
cyber_ros_bridge/lib/module_drivers.cpp:256:35: error: cannot convert 'apollo::canbus::Chassis::brake_percentage' from type 'float (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_brake_percentage_type {aka double}'
     chassis_ros.brake_percentage  = chassis_msg->brake_percentage;
                                   ^
cyber_ros_bridge/lib/module_drivers.cpp:257:38: error: cannot convert 'apollo::canbus::Chassis::steering_percentage' from type 'float (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_steering_percentage_type {aka double}'
     chassis_ros.steering_percentage  = chassis_msg->steering_percentage;
                                      ^
cyber_ros_bridge/lib/module_drivers.cpp:258:37: error: cannot convert 'apollo::canbus::Chassis::steering_torque_nm' from type 'float (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_steering_torque_nm_type {aka double}'
     chassis_ros.steering_torque_nm  = chassis_msg->steering_torque_nm;
                                     ^
cyber_ros_bridge/lib/module_drivers.cpp:259:32: error: cannot convert 'apollo::canbus::Chassis::parking_brake' from type 'bool (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_parking_brake_type {aka unsigned char}'
     chassis_ros.parking_brake  = chassis_msg->parking_brake;
                                ^
cyber_ros_bridge/lib/module_drivers.cpp:260:35: error: cannot convert 'apollo::canbus::Chassis::high_beam_signal' from type 'bool (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_high_beam_signal_type {aka unsigned char}'
     chassis_ros.high_beam_signal  = chassis_msg->high_beam_signal;
                                   ^
cyber_ros_bridge/lib/module_drivers.cpp:261:34: error: cannot convert 'apollo::canbus::Chassis::low_beam_signal' from type 'bool (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_low_beam_signal_type {aka unsigned char}'
     chassis_ros.low_beam_signal  = chassis_msg->low_beam_signal;
                                  ^
cyber_ros_bridge/lib/module_drivers.cpp:262:35: error: cannot convert 'apollo::canbus::Chassis::left_turn_signal' from type 'bool (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_left_turn_signal_type {aka unsigned char}'
     chassis_ros.left_turn_signal  = chassis_msg->left_turn_signal;
                                   ^
cyber_ros_bridge/lib/module_drivers.cpp:263:36: error: cannot convert 'apollo::canbus::Chassis::right_turn_signal' from type 'bool (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_right_turn_signal_type {aka unsigned char}'
     chassis_ros.right_turn_signal  = chassis_msg->right_turn_signal;
                                    ^
cyber_ros_bridge/lib/module_drivers.cpp:264:23: error: cannot convert 'apollo::canbus::Chassis::horn' from type 'bool (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_horn_type {aka unsigned char}'
     chassis_ros.horn  = chassis_msg->horn;
                       ^
cyber_ros_bridge/lib/module_drivers.cpp:265:24: error: cannot convert 'apollo::canbus::Chassis::wiper' from type 'bool (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_wiper_type {aka unsigned char}'
     chassis_ros.wiper  = chassis_msg->wiper;
                        ^
cyber_ros_bridge/lib/module_drivers.cpp:266:35: error: cannot convert 'apollo::canbus::Chassis::disengage_status' from type 'bool (apollo::canbus::Chassis::)()const' to type 'chassis_msgs::chassis_<std::allocator<void> >::_disengage_status_type {aka unsigned char}'
     chassis_ros.disengage_status  = chassis_msg->disengage_status;
                                   ^
cyber_ros_bridge/lib/module_drivers.cpp: In function 'void cyber_ros_bridge::ROSChassisToApolloChassis(const ConstPtr&, apollo::canbus::Chassis&)':
cyber_ros_bridge/lib/module_drivers.cpp:281:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_engine_started'
     chassis_apollo.mutable_engine_started()->set_engine_started(chassis_msg->engine_started);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:282:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_engine_rpm'
     chassis_apollo.mutable_engine_rpm()->set_engine_rpm(chassis_msg->engine_rpm);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:283:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_speed_mps'
     chassis_apollo.mutable_speed_mps()->set_speed_mps(chassis_msg->speed_mps);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:284:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_odometer_m'
     chassis_apollo.mutable_odometer_m()->set_odometer_m(chassis_msg->odometer_m);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:285:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_throttle_percentage'
     chassis_apollo.mutable_throttle_percentage()->set_throttle_percentage(chassis_msg->throttle_percentage);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:286:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_brake_percentage'
     chassis_apollo.mutable_brake_percentage()->set_brake_percentage(chassis_msg->brake_percentage);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:287:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_steering_percentage'
     chassis_apollo.mutable_steering_percentage()->set_steering_percentage(chassis_msg->steering_percentage);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:288:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_steering_torque_nm'
     chassis_apollo.mutable_steering_torque_nm()->set_steering_torque_nm(chassis_msg->steering_torque_nm);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:289:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_parking_brake'
     chassis_apollo.mutable_parking_brake()->set_parking_brake(chassis_msg->parking_brake);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:290:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_high_beam_signal'
     chassis_apollo.mutable_high_beam_signal()->set_high_beam_signal(chassis_msg->high_beam_signal);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:291:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_low_beam_signal'
     chassis_apollo.mutable_low_beam_signal()->set_low_beam_signal(chassis_msg->low_beam_signal);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:292:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_left_turn_signal'
     chassis_apollo.mutable_left_turn_signal()->set_left_turn_signal(chassis_msg->left_turn_signal);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:293:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_right_turn_signal'
     chassis_apollo.mutable_right_turn_signal()->set_right_turn_signal(chassis_msg->right_turn_signal);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:294:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_horn'
     chassis_apollo.mutable_horn()->set_horn(chassis_msg->horn);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:295:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_wiper'
     chassis_apollo.mutable_wiper()->set_wiper(chassis_msg->wiper);
                    ^
cyber_ros_bridge/lib/module_drivers.cpp:296:20: error: 'class apollo::canbus::Chassis' has no member named 'mutable_disengage_status'
     chassis_apollo.mutable_disengage_status()->set_disengage_status(chassis_msg->disengage_status);

**Comment by Prj1508** [comment]
The error message now is 
O: Reading 'startup' options from /home/apollo_ros_bridge/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (10-24 15:36:03.578) Found 2 targets...
ERROR: (10-24 15:36:08.817) /home/apollo_ros_bridge/cyber_ros_bridge/lib/BUILD:4:1: C++ compilation of rule '//cyber_ros_bridge/lib:cyber_ros_bridge_lib' failed (Exit 1).
In file included from ./cyber_ros_bridge/lib/cyber_ros_bridge_lib.hpp:36:0,
                 from cyber_ros_bridge/lib/module_navigation.cpp:21:
./cyber_ros_bridge/lib/Data.hpp:77:15: error: 'chassis_msgs' was not declared in this scope
     DataField<chassis_msgs::chassis> chassis;
               ^
./cyber_ros_bridge/lib/Data.hpp:77:36: error: template argument 1 is invalid
     DataField<chassis_msgs::chassis> chassis;
                                    ^
INFO: (10-24 15:36:08.825) Elapsed time: 5.460s, Critical Path: 5.19s

**Comment by abhilashbalachandran** [comment]
There are detailed instructions on how to setup ROS msgs here: http://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv

**Comment by abhilashbalachandran** [comment]
For most matters regarding ROS, I would also recommend that you post here: https://answers.ros.org/questions/
