### ISSUE TITLE
Not able to get into Apollo docker

### ISSUE THREAD

**Issue by Prj1508** [AuroAi/apollo_ros_bridge#6]
Hi
After commenting out those 3 lines in dev_start.sh, I am not able to get into the docker.  It complains " Error: No such container: apollo_dev_dpt". Please let me know
thanks

**Comment by abhilashbalachandran** [comment]
Can you post the complete console error log?

**Comment by Prj1508** [comment]
Pls see below. I am using 16.04, Apollo 3.5. I am running roscore (roscore && ./bazel-bin/cyber_ros_bridge/cyber_ros_bridge) in another terminal and there is no error there. 


~/apollo-3.5$ ./docker/scripts/dev_start.sh
[sudo] password for pm: 
[INFO] Start docker container based on local image : lgsvl/apollo-3.5:latest
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
yolo3d_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:33add717a675be26c86f817d2207c1ab1ec25694f0decb63e55f0fc3d14b1397
Status: Image is up to date for apolloauto/apollo:yolo3d_volume-x86_64-latest
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
137e284cf50de86cf1278dc41206870546dae558677826cec974612b65f185ec
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:d8be22d8221c784e8a29af14a23be7fc5f2164137ec24228701e6fdcb689b088
Status: Image is up to date for apolloauto/apollo:localization_volume-x86_64-latest
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
b7ea78cbdd788c6c4172bdf711852332212f0167710bde707a94fd72ea434ca7
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
paddlepaddle_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:901f110a4f13501e074f599b2c7d636a7584d290f59ef50237a7d77e66d025fb
Status: Image is up to date for apolloauto/apollo:paddlepaddle_volume-x86_64-latest
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
2361c35385e8ced1354e9300b912bb94db71f66c63e178ab4d8234259506cc9c
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
local_third_party_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:b844c40ab0af0733ce69c38b220a8b14f752bd834f63343392ce8508b98b546b
Status: Image is up to date for apolloauto/apollo:local_third_party_volume-x86_64-latest
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
bc198cb0037e0e86f6fd8680c5cf4145fbe7e9d9232215967f6ea97ac4a86f49
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libopencv_core.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libopencv_core.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[INFO] Starting docker container "apollo_dev_jpm" ...
++ local_volumes
++ volumes='-v /home/jpm/apollo-3.5:/apollo              -v /home/jpm/.cache:/home/jpm/.cache'
++ case "$(uname -s)" in
+++ uname -s
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
++ volumes='-v /home/jpm/apollo-3.5:/apollo              -v /home/jpm/.cache:/home/jpm/.cache -v /dev:/dev                                 -v /media:/media                                 -v /tmp/.X11-unix:/tmp/.X11-unix:rw                                 -v /etc/localtime:/etc/localtime:ro                                 -v /usr/src:/usr/src                                 -v /lib/modules:/lib/modules'
++ echo '-v /home/jpm/apollo-3.5:/apollo              -v /home/jpm/.cache:/home/jpm/.cache -v /dev:/dev                                 -v /media:/media                                 -v /tmp/.X11-unix:/tmp/.X11-unix:rw                                 -v /etc/localtime:/etc/localtime:ro                                 -v /usr/src:/usr/src                                 -v /lib/modules:/lib/modules'
+ nvidia-docker run -it -d --privileged --name apollo_dev_jpm --volumes-from apollo_yolo3d_volume_jpm --volumes-from apollo_localization_volume_jpm --volumes-from apollo_paddlepaddle_volume_jpm --volumes-from apollo_local_third_party_volume_jpm -e DISPLAY=:0 -e DOCKER_USER=jpm -e USER=jpm -e DOCKER_USER_ID=1000 -e DOCKER_GRP=apollo -e DOCKER_GRP_ID=1000 -e DOCKER_IMG=lgsvl/apollo-3.5:latest -e USE_GPU=1 -v /home/jpm/apollo-3.5:/apollo -v /home/jpm/.cache:/home/jpm/.cache -v /dev:/dev -v /media:/media -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /etc/localtime:/etc/localtime:ro -v /usr/src:/usr/src -v /lib/modules:/lib/modules --net host -w /apollo
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
+ --shm-size 2G --pid=host -v /dev/null:/dev/raw1394 lgsvl/apollo-3.5:latest /bin/bash
./docker/scripts/dev_start.sh: line 336: --shm-size: command not found
+ set +x
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Error: No such container: apollo_dev_jpm
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
pm@devI:~/apollo-3.5$ ./docker/scripts/dev_into.sh
Error: No such container: apollo_dev_jpm
pm@dev:~/apollo-3.5$

**Comment by Prj1508** [comment]
I am running Apollo within LGSLV Simulator and also I can get into the container when those 3 lines in dev_start.sh is not commented out

**Comment by abhilashbalachandran** [comment]
Hi @Prj1508 . Thanks for bringing up the issue. I have updated the Readme.md file to reflect the changes. Basically, do not comment out the three lines in dev_start.sh

**Comment by Prj1508** [comment]
Thank you. I am now able to run apollo and cyber_monitor alongside apollo-ros bridge. 
However, I am not seeing any updates of the topics with rostopic echo on bridge side while cyber_monitor is publishing messages ( with LGSLV). What should I do to see these topics on ROS side? Here is the screen shot 

/home/jpm/Pictures/RA_Screenshot from 2019-09-18 17-43-45.png

**Comment by Prj1508** [comment]
![RA_Screenshot from 2019-09-18 17-43-45](https://user-images.githubusercontent.com/48227055/65188423-62ae6500-da3c-11e9-87b0-f525119e9dcd.png)

**Comment by Prj1508** [comment]
![ra3_Screenshot from 2019-09-18 17-51-07](https://user-images.githubusercontent.com/48227055/65188671-eff1b980-da3c-11e9-96fd-9c033c21392c.png)

**Comment by abhilashbalachandran** [comment]
@Prj1508 So, to get the bridging working, you need to launch the bridge binary
Inside the apollo_ros_bridge container:
1. Build the code with 
```
bazel build cyber_ros_bridge:all
```
2. run the example node
```
roscore && ./bazel-bin/cyber_ros_bridge/cyber_ros_bridge
```
3. Now you should be able to see the topics being converted to ros messages which can be viewed with 
```
rostopic list
```
Note:: Make sure the topic names are set properly inside the yaml file in the yaml_defs folder
Currently, 
```
apollo::drivers::PointCloud to sensor_msgs::PointCloud2
apollo::localization::LocalizationEstimate to nav_msgs::Odom 
apollo::planning::ADCTrajectory to nav_msgs::Path
sensor_msgs::PointCloud2 to apollo::drivers::PointCloud
```
are the only ones implemented in the example. You can implement your own bridging for any topics with the following document 
https://github.com/AuroAi/apollo_ros_bridge/blob/master/docs/How_to_add_a_new_message_conversion_for_the_bridge.md
and 
https://github.com/AuroAi/apollo_ros_bridge/blob/master/docs/adding_custom_bridging.md

**Comment by abhilashbalachandran** [comment]
Closing this issue and opening a new one for getting bridge topics listed  https://github.com/AuroAi/apollo_ros_bridge/issues/7#issue-495479965
